import os
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, flash, redirect, render_template, request, url_for
from psycopg2.extras import execute_values

from lakebase import get_connection

load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "databricks-support-demo")

STATUSES = ("open", "in_progress", "resolved")
PRIORITIES = ("low", "medium", "high")


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'in_progress', 'resolved')),
    priority VARCHAR(20) NOT NULL DEFAULT 'medium'
        CHECK (priority IN ('low', 'medium', 'high')),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    message_text TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id
    ON ticket_messages(ticket_id, created_at);
"""

SAMPLE_TICKETS = [
    ("Cannot access analytics dashboard", "open", "high", "Maya"),
    ("Password reset email not received", "in_progress", "medium", "Jordan"),
    ("Exported CSV has incorrect dates", "resolved", "low", "Priya"),
]

SAMPLE_MESSAGES = [
    (0, "The dashboard returns a permission denied message.", "Maya"),
    (0, "We are checking the workspace permissions now.", "Support Agent"),
    (1, "I requested two resets but no email arrived.", "Jordan"),
    (1, "Please check spam; we are also reviewing the mail logs.", "Support Agent"),
    (2, "Dates appear one day earlier in the downloaded file.", "Priya"),
    (2, "The timezone conversion was corrected and verified.", "Support Agent"),
]


def initialize_database():
    """Create required tables and seed exactly once when no tickets exist."""
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
        cur.execute("SELECT COUNT(*) AS count FROM tickets")
        if cur.fetchone()["count"] == 0:
            execute_values(
                cur,
                """INSERT INTO tickets (title, status, priority, created_by)
                   VALUES %s RETURNING ticket_id""",
                SAMPLE_TICKETS,
            )
            ticket_ids = [row["ticket_id"] for row in cur.fetchall()]
            messages = [
                (ticket_ids[index], text, author)
                for index, text, author in SAMPLE_MESSAGES
            ]
            execute_values(
                cur,
                """INSERT INTO ticket_messages (ticket_id, message_text, author)
                   VALUES %s""",
                messages,
            )
        conn.commit()


@app.template_filter("friendly_time")
def friendly_time(value):
    if not value:
        return ""
    return value.astimezone(timezone.utc).strftime("%b %d, %Y · %H:%M UTC")


@app.get("/")
def index():
    status_filter = request.args.get("status", "all")
    if status_filter not in (*STATUSES, "all"):
        status_filter = "all"

    where = "WHERE t.status = %s" if status_filter != "all" else ""
    params = (status_filter,) if status_filter != "all" else ()
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            f"""SELECT t.*, COUNT(m.message_id) AS message_count
                FROM tickets t
                LEFT JOIN ticket_messages m ON m.ticket_id = t.ticket_id
                {where}
                GROUP BY t.ticket_id
                ORDER BY t.created_at DESC""",
            params,
        )
        tickets = cur.fetchall()
        cur.execute("SELECT status, COUNT(*) AS count FROM tickets GROUP BY status")
        counts = {row["status"]: row["count"] for row in cur.fetchall()}

    return render_template(
        "index.html",
        tickets=tickets,
        counts=counts,
        statuses=STATUSES,
        status_filter=status_filter,
    )


@app.get("/tickets/<int:ticket_id>")
def ticket_detail(ticket_id):
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute("SELECT * FROM tickets WHERE ticket_id = %s", (ticket_id,))
        ticket = cur.fetchone()
        if not ticket:
            flash("Ticket not found.", "error")
            return redirect(url_for("index"))
        cur.execute(
            """SELECT * FROM ticket_messages
               WHERE ticket_id = %s ORDER BY created_at, message_id""",
            (ticket_id,),
        )
        messages = cur.fetchall()
    return render_template(
        "ticket.html", ticket=ticket, messages=messages, statuses=STATUSES
    )


@app.post("/tickets")
def create_ticket():
    title = request.form.get("title", "").strip()
    created_by = request.form.get("created_by", "").strip()
    priority = request.form.get("priority", "medium")
    if not title or not created_by:
        flash("Title and creator are required.", "error")
        return redirect(url_for("index"))
    if len(title) > 200 or len(created_by) > 100 or priority not in PRIORITIES:
        flash("Check the title, creator, and priority values.", "error")
        return redirect(url_for("index"))

    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            """INSERT INTO tickets (title, status, priority, created_by)
               VALUES (%s, 'open', %s, %s) RETURNING ticket_id""",
            (title, priority, created_by),
        )
        ticket_id = cur.fetchone()["ticket_id"]
        conn.commit()
    flash("Ticket created.", "success")
    return redirect(url_for("ticket_detail", ticket_id=ticket_id))


@app.post("/tickets/<int:ticket_id>/messages")
def add_message(ticket_id):
    text = request.form.get("message_text", "").strip()
    author = request.form.get("author", "").strip()
    if not text or not author or len(author) > 100:
        flash("Message and author are required.", "error")
        return redirect(url_for("ticket_detail", ticket_id=ticket_id))

    with get_connection() as conn, conn.cursor() as cur:
        cur.execute("SELECT 1 FROM tickets WHERE ticket_id = %s", (ticket_id,))
        if not cur.fetchone():
            flash("Ticket not found.", "error")
            return redirect(url_for("index"))
        cur.execute(
            """INSERT INTO ticket_messages (ticket_id, message_text, author)
               VALUES (%s, %s, %s)""",
            (ticket_id, text, author),
        )
        conn.commit()
    flash("Message added.", "success")
    return redirect(url_for("ticket_detail", ticket_id=ticket_id))


@app.post("/tickets/<int:ticket_id>/status")
def update_status(ticket_id):
    status = request.form.get("status", "")
    if status not in STATUSES:
        flash("Choose a valid status.", "error")
        return redirect(url_for("ticket_detail", ticket_id=ticket_id))

    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "UPDATE tickets SET status = %s WHERE ticket_id = %s",
            (status, ticket_id),
        )
        if cur.rowcount == 0:
            flash("Ticket not found.", "error")
            return redirect(url_for("index"))
        conn.commit()
    flash("Status updated.", "success")
    return redirect(url_for("ticket_detail", ticket_id=ticket_id))


@app.get("/healthz")
def healthz():
    return {"status": "ok", "time": datetime.now(timezone.utc).isoformat()}


if __name__ == "__main__":
    initialize_database()
    app.run(host="0.0.0.0", port=int(os.environ.get("DATABRICKS_APP_PORT", "8000")))

